# Generated by Django 5.1.1 on 2024-09-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(max_length=50, unique=True)),
                ('allergen_desc', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=50, unique=True)),
                ('activity_desc', models.CharField(max_length=150, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserAllergens',
            fields=[
                ('user_allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.allergens')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.users')),
            ],
            options={
                'unique_together': {('user_id', 'allergen_id')},
            },
        ),
        migrations.CreateModel(
            name='UserActivities',
            fields=[
                ('user_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.activities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.users')),
            ],
            options={
                'unique_together': {('user_id', 'activity_id')},
            },
        ),
        migrations.CreateModel(
            name='PlannedActivities',
            fields=[
                ('planned_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.activities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.users')),
            ],
            options={
                'unique_together': {('user_id', 'activity_id', 'start_date', 'end_date')},
            },
        ),
    ]
