# Generated by Django 5.1.1 on 2024-10-05 19:05

import django.contrib.auth.password_validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.validate_password])),
                ('address', models.CharField(max_length=250, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=50, unique=True)),
                ('activity_desc', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(max_length=50, unique=True)),
                ('allergen_desc', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Allergens',
            },
        ),
        migrations.CreateModel(
            name='PlannedActivities',
            fields=[
                ('planned_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.activities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PlannedActivities',
                'unique_together': {('user_id', 'activity_id', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='UserActivities',
            fields=[
                ('user_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.activities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserActivities',
                'unique_together': {('user_id', 'activity_id')},
            },
        ),
        migrations.CreateModel(
            name='UserAllergens',
            fields=[
                ('user_allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po_app.allergens')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserAllergens',
                'unique_together': {('user_id', 'allergen_id')},
            },
        ),
    ]
