# Generated by Django 5.1.1 on 2024-09-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='allergens',
            options={'verbose_name_plural': 'Allergens'},
        ),
        migrations.AlterModelOptions(
            name='plannedactivities',
            options={'verbose_name_plural': 'PlannedActivities'},
        ),
        migrations.AlterModelOptions(
            name='useractivities',
            options={'verbose_name_plural': 'UserActivities'},
        ),
        migrations.AlterModelOptions(
            name='userallergens',
            options={'verbose_name_plural': 'UserAllergens'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='activities',
            name='user_id',
        ),
    ]
